with open('input1.txt', 'r') as input_file: input_data = [int(i) for i in input_file.read().split('\n')]; print(str([x for x in [[z1 * z2 for z2 in input_data[count1:] if z1 + z2 == 2020] for count1, z1 in enumerate(input_data)] if x][0][0]) + '\n' + str([y for y in [[x for x in [[z1 * z2 * z3 for z3 in input_data[count2:] if z1 + z2 + z3 == 2020] for count2, z2 in enumerate(input_data[count1:])] if x] for count1, z1 in enumerate(input_data)] if y][0][0][0]))

with open('input2.txt', 'r') as input_file: input_list = [[[int(n) for n in i.split(' ')[0].split('-')], i.split(' ')[1][0], i.split(' ')[2]] for i in input_file.read().split('\n')]; print(str([(pwd[2].count(pwd[1]) >= pwd[0][0]) and (pwd[2].count(pwd[1]) <= pwd[0][1]) for pwd in input_list].count(True)) + '\n' + str([(pwd[2][pwd[0][0] - 1] == pwd[1]) ^ (pwd[2][pwd[0][1] - 1] == pwd[1]) for pwd in input_list].count(True)))

with open('input3.txt', 'r') as input_file: input_map = [[field == '#' for field in line] for line in input_file.read().split('\n')]; print(str([line[(pos * 3) % len(line)] for pos, line in enumerate(input_map)].count(True)) + '\n' + str(eval('*'.join([str(i) for i in [[line[(pos * slope[0]) % len(line)] for pos, line in enumerate([n for c, n in enumerate(input_map) if c % slope[1] == 0])].count(True) for slope in [[1, 1], [3, 1], [5, 1], [7, 1], [1, 2]]]]))))

with open('input4.txt', 'r') as input_file: passports = [{i.split(':')[0]: i.split(':')[1] for i in passport.replace('\n', ' ').split(' ')} for passport in input_file.read().split('\n\n')]; print(str([all([field in passport for field in ('byr', 'iyr', 'eyr', 'hgt', 'hcl', 'ecl', 'pid')]) for passport in passports].count(True)) + '\n' + str([all([field in passport for field in ('byr', 'iyr', 'eyr', 'hgt', 'hcl', 'ecl', 'pid')]) and all([len(passport['byr']) == 4 and (1920 <= int(passport['byr']) <= 2002), len(passport['iyr']) == 4 and (2010 <= int(passport['iyr']) <= 2020), len(passport['eyr']) == 4 and (2020 <= int(passport['eyr']) <= 2030), passport['hgt'][-2:] in ('cm', 'in') and ((150 <= int(passport['hgt'][:-2]) <= 193) if passport['hgt'][-2:] == 'cm' else (59 <= int(passport['hgt'][:-2]) <= 76)), passport['hcl'][0] == '#' and len(passport['hcl']) == 7 and all([i in list('0123456789abcdef') for i in passport['hcl'][1:]]), passport['ecl'] in ('amb', 'blu', 'brn', 'gry', 'grn', 'hzl', 'oth'), len(passport['pid']) == 9 and all([i in list('0123456789') for i in passport['pid']])]) for passport in passports].count(True)))

with open('input5.txt', 'r') as input_file: seat_codes = input_file.read().replace('F', '0').replace('B', '1').replace('L', '0').replace('R', '1').split('\n'); seat_ids = [int(i[:7], 2) * 8 + int(i[7:], 2) for i in seat_codes]; print(str(max(seat_ids)) + '\n' + str((seat_ids[[(i + 1 not in seat_ids) and (i + 2 in seat_ids) for i in seat_ids].index(True)] + 1)))
